# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
