# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_auto_20181005_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
